[pytest]
asyncio_mode = auto
testpaths = tests
python_files = test_*.py
filterwarnings =
    ignore::pydantic.PydanticDeprecatedSince20
    ignore::DeprecationWarning:sqlalchemy.*
    ignore::DeprecationWarning:datetime.*
