"""Add CMS models fix

Revision ID: f1d9e8001da8
Revises: 4539779c0812
Create Date: 2026-05-25 16:14:19.705510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f1d9e8001da8'
down_revision: Union[str, Sequence[str], None] = '4539779c0812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=False))
        batch_op.drop_constraint(batch_op.f('posts_ibfk_5'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.drop_column('status')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('menu_id')
        batch_op.drop_column('created_by')
        batch_op.drop_column('published_at')
        batch_op.drop_column('custom_fields_values')
        batch_op.drop_column('submenu_id')
        batch_op.drop_column('subcategory_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('submenu_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('custom_fields_values', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('published_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('menu_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_featured', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('posts_ibfk_5'), 'users', ['created_by'], ['id'])
        batch_op.drop_column('is_published')
        batch_op.drop_column('meta_data')

    # ### end Alembic commands ###
